pub mod agent_profile;
pub mod app_paths;
pub mod config;
pub mod diagnostic;
pub mod initializer;
pub mod lock;
pub mod model;
pub mod parser;
pub mod path_security;
pub mod pointer_prompt;
pub mod profile_registry;
pub mod project_registry;
pub mod project_scanner;
pub mod push_attempt;
pub mod runtime_store;
pub mod session_route;
pub mod task_id;
pub mod task_store;
pub mod transaction;
pub mod validation;
pub mod watcher;

pub use config::CoreConfig;
pub use diagnostic::{Diagnostic, DiagnosticCode, Severity};
pub use model::{ProjectDocument, TaskDocument, TaskState};
